### ISSUE TITLE
Fix sidebar on mobile screens

### ISSUE THREAD

**Issue by misterupkeep** [misterupkeep/Lychee-front#2]
User CSS which fixes it:
```css
.sidebar__wrapper {
  width: 100% !important;
}
```

It's set to a fixed px size for whatever reason; might even be an upstream issue
